# These are supported funding model platforms

github: adriangb

# Please donate to the following projects which Xpresso relies on:
# - https://github.com/samuelcolvin/pydantic
# - https://github.com/encode
