# These are supported funding model platforms

github: adriangb

# Please also consider donating to the following projects which Xpresso relies on:
# - https://github.com/samuelcolvin/pydantic
# - https://github.com/encode
