comment:
  layout: "diff, files"
  require_changes: true
codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%  # the leniency in hitting the target
