site_name: "Xpresso"
site_description: Developer centric, performant and extensible ASGI framework
site_url: https://www.xpresso-api.dev

theme:
  name: "material"
  logo: assets/images/xpresso-bean.png
  favicon: assets/images/xpresso-bean.png
  custom_dir: docs/overrides
  palette:
    - scheme: "default"
      primary: "black"
      accent: "amber"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/weather-night"
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: "black"
      accent: "amber"
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to light mode"

repo_name: adriangb/xpresso
repo_url: https://github.com/adriangb/xpresso
edit_uri: "blob/main/docs/"

nav:
  - Xpresso: "README.md"
  - Python Types: "types.md"
  - Tutorial:
    - Minimal App: "tutorial/minimal_app.md"
    - Path Parameters: "tutorial/path_params.md"
    - Query Parameters: "tutorial/query_params.md"
    - Parameter Constraints and Metadata: "tutorial/param_constraints_and_metadata.md"
    - Request Body: "tutorial/body.md"
    - Cookie Parameters: "tutorial/cookie_params.md"
    - Header Parameters: "tutorial/header_params.md"
    - File Uploads: "tutorial/files.md"
    - Forms: "tutorial/forms.md"
    - Dependencies:
      - Introduction: "tutorial/dependencies/README.md"
      - Nested Dependencies: "tutorial/dependencies/nested.md"
      - Dependency Lifecycle: "tutorial/dependencies/lifecycle.md"
      - HTTP Parameter Dependencies: "tutorial/dependencies/http-params.md"
      - Scopes: "tutorial/dependencies/scopes.md"
      - Shared Dependencies: "tutorial/dependencies/shared.md"
    - Middleware:
      - Introduction: "tutorial/middleware/README.md"
    - Lifespans: "tutorial/lifespan.md"
    - Routing: "tutorial/routing.md"
    - CORS: tutorial/cors.md
  - Advanced Usage:
    - WebSockets: advanced/websockets.md
    - Dependencies:
      - Performance: "advanced/dependencies/performance.md"
      - Caching: "advanced/dependencies/caching.md"
      - Accessing Responses: "advanced/dependencies/responses.md"
      - Provider Registration and Testing: "advanced/dependencies/registration-and-testing.md"
    - Binders: advanced/binders.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
  - search:
